apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: board-service
  template:
    metadata:
      labels:
        app: board-service
    spec:
      containers:
        - name: board-service
          image: board-service:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-service:8761/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: board-service
spec:
  type: ClusterIP
  selector:
    app: board-service
  ports:
    - port: 8080
      targetPort: 8080